#!/bin/bash

REBUILD=${REBUILD:-false}

ROOT=${ROOT:-$(pwd)}
HOST=${HOST:-$ROOT/devices/$(arch)/usr}
PREFIX=${PREFIX:-${ROOT}/devices/emsdk/usr}

PYTHON_FOR_BUILD=${PYTHON_FOR_BUILD:-${HOST}/bin/python3}

#stable
EMFLAVOUR=latest
#git
EMFLAVOUR=tot

PYDK_PYTHON_HOST_PLATFORM=wasm32-$EMFLAVOUR-emscripten

if [[ ! -z ${PYDK+z} ]]
then
    # config already set
    echo -n
else
    mkdir -p src
    export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"
    export LD_LIBRARY_PATH="${HOST}/lib:$LD_LIBRARY_PATH"
    export PATH="$HOST/bin:$PATH"
    export PYDK=minimal
fi


