name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pygame-wasm-builder prepare
      run: |
            WD=$(pwd)
            python3 -V
            echo $WD
            clang --version | head -n 1
            echo
            gcc --version | head -n 1
            echo
            env|grep GITHUB
            echo
            grep "^Pkg.Revision =" ${ANDROID_HOME}/ndk-bundle/source.properties
            sudo apt-get update
            sudo apt-get install -y bash wget
            cd $GITHUB_WORKSPACE
            echo adding emscripten support
            git clone https://github.com/emscripten-core/emsdk.git
            cd emsdk && ./emsdk install tot && ./emsdk activate tot
            cd $GITHUB_WORKSPACE
            echo " === Building  ===="
            time bash ./python-wasm-plus.sh
            time bash ./buildapp.sh
            cd $GITHUB_WORKSPACE
            mv build/demo $GITHUB_WORKSPACE/
            du -hs demo/*

    - name : "Upload to GitHub pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: demo
