name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: pygame-wasm-builder prepare
      run: |
            WD=$(pwd)
            python3 -V
            echo $WD
            clang --version | head -n 1
            echo
            gcc --version | head -n 1
            echo
            env|grep GITHUB
            echo
            env|grep ANDROID
            sudo apt-get update
            sudo apt-get install -y bash wget

    - name: build
      run: |
            echo " === Building  ===="
            cd $GITHUB_WORKSPACE
            time bash ./python-wasm-plus.sh
            du -hs prebuilt/emsdk/libpy*

    - name: pack
      run: | 
            echo " === Packaging ==="
            time bash ./buildapp.sh
            cd $GITHUB_WORKSPACE
            mv build/demo $GITHUB_WORKSPACE/
            du -hs demo/*

    - name : "Upload to GitHub pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: demo
